apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dyndns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: doddns
              image: thepiconerd/digitaloceandyndns
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: digitalocean
                      key: apiKey
              args:
                - "--config /etc/config/config.yaml"
              volumeMounts:
                - name: config
                  mountPath: /etc/config
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: doddns-config